[package]
name = "list-ec2-instances"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[dependencies]
docopt = "0.7"
futures = "0.1.18"
rusoto_core = "0.32.0"
rusoto_ec2 = "0.32.0"
rustc-serialize = "0.3.24"
