[package]
name = "list-ec2-instances"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[[bin]]
name = "list_ec2_instances"
path = "src/list_ec2_instances.rs"

[dependencies]
getopts = "0.2.21"
rusoto_core = "0.42.0"
rusoto_ec2 = "0.42.0"
rustc-serialize = "0.3.24"
