[package]
name = "list-ec2-instances"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[dependencies]
docopt = "0.7"
rusoto = {version = "0.20", features = ["ec2"]}
rustc-serialize = "0.3"
